### ISSUE TITLE
Is this repository a joke?

### ISSUE THREAD

**Issue by samclaus** [k3nsei/ng-in-viewport#1283]
From what I can tell, by scouring your dozens of files, it does not seem like you actually add any useful functionality on top of the built-in [`IntersectionObserver` API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

Instead, it seems you just wrapped what should be a simple, standard (already thoroughly tested) API with dozens of configuration files and end-to-end tests of your own. Not to mention several layers of directory structure.

Please, please, PLEASE tell me this library is a joke. Almost 800 commits for nothing but a bloated codebase if you import the library? If this is not a joke, and you have been mislead into believing Angular-izing everything is the way to a better world, I am very sorry.

Please see this [Enterprise FizzBuzz repository](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition), which is a joke mocking detrimental Java coding styles.

Anyways, maybe you are forced to work with Angular at your job. I still think repositories like this spread the wrong message to new programmers about "best practices". I understand you need to make a living, but surely there are alternatives ways to do it that eat less of your time AND result in a nicer internet.

**Comment by k3nsei** [comment]
You can build a house using only sticks. You can build SPA with only native JS DOM APIs. But there is concept of higher abstraction in computer science, and examples of that are frameworks like Angular or React. They are wrapping "well tested" not! browser APIs (browsers still have bugs) and gives developers opportunities to have nicer experience and do their work faster and do not repeat themselves. This library have many years of history and was usefull even when there was no IntersectionObserver yet. Today it's a bridge between Angular and native browser code to be used in optimal and performant way. It for example reuses same IntersectionObserver instance when attached to different element with same config.

Thanks for your opinion. You have right to have one. But if you don't like it so much instead of writing your frustrations here you should do something else that will make you happier. I don't know maybe do what is my latest hobby and ride some bicycle or fly FPV drone. Have a good luck in you life.

I'm closing this issue it's again any code of conduct of OSS.
